### ISSUE TITLE
thread main panicked at called Option::unwrap() on a None value, src\site_generator.rs:298:26

### ISSUE THREAD

**Issue by CleanCodeDeveloper** [thecodrr/docgen#3]
Hello,
thank you for giving the doctave project a new home and a future! 

I ran into some issues trying to migrate my doctave project to docgen:
![Screenshot docgen error](https://user-images.githubusercontent.com/16760760/227348733-f3242e8f-a4dd-446e-9060-35b4dc5c161c.jpg)

Is it possible to get a more detailed error message? This leaves me clueless what i did wrong.

Kind Regards :)

**Comment by thecodrr** [comment]
@CleanCodeDeveloper I completely missed this issue, sorry about that! Are you still having this problem?

I do want to remind you that this project is still quite unstable & not documented at all. All the changes I made to it are only documented in the release notes.
